'use client';
import {useState} from 'react';
import Link from 'next/link';
import {Search,MapPin,Phone,MessageCircle,Clock3,Menu,X,ChevronRight,ArrowUpRight,Store,Package,Tag,Inbox,BarChart3,Settings2,Plus} from 'lucide-react';
import {commerces,categories as catalogCategories} from '../lib/catalog';

const cats=catalogCategories.map(x=>x.name);
const shops=[
 ['Kiosco La Esquina','Kiosco','Av. Boulogne Sur Mer 742, Las Heras','261 555 1040','5492615551040','08:00–23:30',['Bebidas','Snacks','Recargas']],
 ['Mendoza Motor','Taller mecánico','Av. San Martín 1840, Las Heras','261 555 2211','5492615552211','08:30–19:00',['Service','Frenos','Diagnóstico']],
 ['Repuestos Cuyo','Casa de repuestos','Videla Castillo 1120, Maipú','261 555 4477','5492615554477','08:30–18:30',['Fiat','Renault','VW']],
 ['Ferretería El Andino','Ferretería','Belgrano 1635, Maipú','261 555 6633','5492615556633','08:00–19:30',['Herramientas','Obra','Hogar']]
] as const;

function Header({admin}:{admin:()=>void}){const[o,setO]=useState(false);return <header><div className="head"><a className="logo"><span>SB</span><b>SmartBarrio</b></a><nav className={o?'open':''}><a href="#categorias">Categorías</a><a href="#comercios">Comercios</a><a href="#como">Cómo funciona</a><a href="#registro">Registrá tu negocio</a></nav><button className="login" onClick={admin}><Settings2 size={15}/> Administrar</button><button className="menu" onClick={()=>setO(!o)}>{o?<X/>:<Menu/>}</button></div></header>}

function Card({s}:{s:typeof shops[number]}){const commerce=commerces.find(c=>c.name===s[0]);return <article className="card"><div className="photo"><Store size={30}/><small>VERIFICADO</small></div><div className="cardbody"><label>● {s[1]}</label><h3>{commerce?<Link href={`/comercio/${commerce.slug}`}>{s[0]}</Link>:s[0]}</h3><p>Productos y servicios para resolver lo que necesitás, cerca de vos.</p><div className="meta"><span><MapPin/> {s[2]}</span><span><Clock3/> {s[5]}</span></div><div className="tags">{s[6].map(x=><i key={x}>{x}</i>)}</div><div className="actions"><a href={`https://wa.me/${s[4]}`} className="btn primary"><MessageCircle/> WhatsApp</a><a href={`tel:${s[3].replaceAll(' ','')}`} className="btn light"><Phone/> Llamar</a></div></div></article>}

function Public({admin}:{admin:()=>void}){return <><Header admin={admin}/><main><section className="hero"><div><label>COMERCIOS LOCALES · MENDOZA</label><h1>Encontrá lo que necesitás <em>cerca tuyo.</em></h1><p>Descubrí comercios, productos y servicios de tu barrio. Contactá directo por WhatsApp o encontrá cómo llegar.</p><div className="search"><Search/><input aria-label="Buscar comercios y productos" placeholder="¿Qué estás buscando?"/><button>Buscar</button></div><div className="quick">Buscá por: {catalogCategories.slice(0,4).map(x=><Link href={`/categoria/${x.slug}`} key={x.slug}>{x.name}</Link>)}</div></div><aside className="featured"><b>COMERCIOS DESTACADOS</b>{shops.slice(0,2).map(s=><div className="mini" key={s[0]}><span><Store/></span><div><strong>{s[0]}</strong><small>{s[1]} · {s[2]}</small></div></div>)}<a href="#comercios">Ver todos <ArrowUpRight/></a></aside></section><section id="categorias" className="section"><div className="title"><div><label>EXPLORÁ</label><h2>¿Qué necesitás?</h2></div><a href="#comercios">Ver todas <ChevronRight/></a></div><div className="categories">{catalogCategories.map(x=><Link href={`/categoria/${x.slug}`} key={x.slug}><span><Store/></span><b>{x.name}</b><ChevronRight/></Link>)}</div></section><section id="comercios" className="section"><div className="title"><div><label>CERCA DE VOS</label><h2>Comercios destacados</h2></div><span className="place"><MapPin/> Mendoza</span></div><div className="grid">{shops.map(s=><Card key={s[0]} s={s}/>)}</div><div className="center"><button className="outline">Ver más comercios <ArrowUpRight/></button></div></section><section id="como" className="how"><div><label>ASÍ DE SIMPLE</label><h2>Del barrio a tu pantalla.</h2><p>SmartBarrio conecta personas con comercios locales sin intermediarios.</p></div><div className="steps"><div><b>01</b><strong>Buscá</strong><span>Por categoría o ubicación.</span></div><div><b>02</b><strong>Elegí</strong><span>Conocé productos y horarios.</span></div><div><b>03</b><strong>Contactá</strong><span>WhatsApp, llamada o cómo llegar.</span></div></div></section><section id="registro" className="register"><div><label>PARA COMERCIOS</label><h2>Tu negocio también puede estar acá.</h2><p>Una presencia digital simple y profesional para recibir consultas.</p></div><button className="btn primary">Registrá tu negocio <ArrowUpRight/></button></section></main><footer><div className="logo"><span>SB</span><b>SmartBarrio</b></div><span>Presencia digital para comercios locales de Mendoza · © 2026</span></footer></>}

function Dashboard({publico}:{publico:()=>void}){const[t,setT]=useState('Inicio');const nav=[['Inicio',BarChart3],['Mi negocio',Store],['Productos',Package],['Promociones',Tag],['Consultas',Inbox]] as const;return <div className="dashboard"><aside><div className="dashlogo"><span>SB</span><b>SmartBarrio</b></div><div className="account"><b>KE</b><span>Kiosco La Esquina<small>Kiosco · Las Heras</small></span></div><nav>{nav.map(([n,I])=><button className={t===n?'active':''} onClick={()=>setT(n)} key={n}><I/> {n}</button>)}</nav><button className="public" onClick={publico}>Ver sitio público <ArrowUpRight/></button></aside><div className="dashmain"><header className="dashhead"><div><label>PANEL DEL COMERCIO</label><h1>{t}</h1></div><button className="btn light" onClick={publico}>Ver sitio</button></header>{t==='Inicio'?<><div className="metrics">{[['Visitas','1.284','+18%'],['Consultas','37','+12%'],['WhatsApp','84','+24%'],['Cómo llegar','51','+9%']].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]} este mes</small></div>)}</div><div className="dashgrid"><section className="panel"><label>ACTIVIDAD</label><h2>Interacciones</h2><div className="chart">{Array.from({length:24},(_,i)=><i style={{height:(30+(i*19)%70)+'%'}} key={i}/>)}</div></section><section className="panel"><label>ÚLTIMAS</label><h2>Consultas</h2>{['María Gómez','Carlos Pérez','Lucía Sosa'].map(n=><div className="query" key={n}><b>{n[0]}</b><span>{n}<small>Consulta reciente</small></span><MessageCircle/></div>)}</section></div></>:<section className="panel editor"><label>CONFIGURACIÓN</label><h2>{t}</h2><input defaultValue="Kiosco La Esquina"/><select defaultValue="Kiosco"><option>Kiosco</option><option>Almacén</option></select><textarea defaultValue="Bebidas, snacks, golosinas y recargas cerca de casa."/><button className="btn primary"><Plus/> Guardar cambios</button></section>}</div></div>}

export default function App(){const[a,setA]=useState(false);return a?<Dashboard publico={()=>setA(false)}/>:<Public admin={()=>setA(true)}/>}