import Link from 'next/link';
import {ArrowUpRight,MapPin,Search,Store,Navigation,CheckCircle2,BarChart3,MessageCircle,Globe2,Zap} from 'lucide-react';
import {categories,commerces,zones} from '@/lib/data';
import {PublicHeader} from '@/components/PublicHeader';
import {PublicFooter} from '@/components/PublicFooter';

const plans=[
{name:'Plan 1',title:'Soporte técnico',price:'ARS 50.000',period:'por mes',items:['Soporte técnico','Mantenimiento','Informes']},
{name:'Plan 2',title:'Soporte + estrategia',price:'ARS 100.000',period:'por mes',items:['Soporte técnico','SEO / Web / GBP / GEO','Mantenimiento y mejora continua']},
{name:'Plan 3',title:'Soporte + estrategia + SEM',price:'ARS 150.000',period:'por mes',items:['Soporte técnico','SEO / Web / GBP / GEO','Estrategia y captación SEM']}
];

export default function Home(){return <div className="site-wrap" id="top"><PublicHeader/><main className="public-main">
<section className="hero-card commercial-hero"><div className="hero-copy"><div className="eyebrow"><span className="dot green"></span>Marketplace local · Mendoza</div><h1>Tu negocio, visible donde tus clientes buscan.</h1><p>SmartBarrio conecta comercios de barrio con personas de Las Heras y Maipú mediante una presencia digital simple, navegable y preparada para generar consultas.</p><div className="hero-actions"><a className="btn primary" href="https://socios.pedidosya.com.ar/es" target="_blank" rel="noreferrer"><Store size={18}/> Registrá tu negocio</a><a className="btn secondary" href="#categorias-negocios"><Search size={18}/> Ver categorías</a></div><div className="trust-row"><span><MapPin size={15}/> Las Heras</span><span><MapPin size={15}/> Maipú</span><span><CheckCircle2 size={15}/> PMV activo</span></div></div><div className="hero-visual green"><div className="visual-badge">SmartBarrio</div><div className="visual-initials">SB</div><div className="visual-caption"><MapPin size={15}/> Marketplace local de Mendoza</div></div></section>

<section id="beneficios" className="market-section commercial-section"><div className="section-head"><div><span className="kicker">BENEFICIOS</span><h2>Una presencia digital pensada para convertir búsquedas en contacto.</h2></div></div><div className="benefit-grid"><article className="benefit-card"><Globe2 size={22}/><h3>Presencia local</h3><p>Tu negocio aparece organizado por categoría y zona para facilitar el descubrimiento.</p></article><article className="benefit-card"><MessageCircle size={22}/><h3>Más consultas</h3><p>Accesos directos a WhatsApp, teléfono, ubicación y datos clave del negocio.</p></article><article className="benefit-card"><BarChart3 size={22}/><h3>Medición</h3><p>Información para entender visitas, acciones y oportunidades de contacto.</p></article><article className="benefit-card"><Zap size={22}/><h3>Actualización continua</h3><p>La propuesta puede evolucionar con tu negocio, productos, servicios y promociones.</p></article></div></section>

<section id="categorias-negocios" className="market-section"><div className="section-head"><div><span className="kicker">CATEGORÍAS DE NEGOCIOS</span><h2>Encontrá negocios por rubro.</h2></div><span className="section-note">{Object.keys(categories).length} rubros disponibles</span></div><div className="market-grid">{Object.entries(categories).map(([slug,name])=><Link className="market-card" href={'/categoria/'+slug} key={slug}><div><span className="market-icon"><Store size={18}/></span><h3>{name}</h3><p>Explorá comercios, productos y servicios.</p></div><ArrowUpRight size={16}/></Link>)}</div></section>

<section id="zonas" className="market-section"><div className="section-head"><div><span className="kicker">ZONAS</span><h2>Explorá por ubicación</h2></div></div><div className="zone-grid">{Object.entries(zones).map(([slug,name])=><Link className="zone-card" href={'/categoria/kioscos?zona='+slug} key={slug}><MapPin size={18}/><div><strong>{name}</strong><span>{commerces.filter(c=>c.zone===slug).length} comercios demo</span></div><Navigation size={15}/></Link>)}</div></section>

<section id="inversion" className="market-section commercial-section"><div className="section-head"><div><span className="kicker">INVERSIÓN</span><h2>Elegí el nivel de acompañamiento.</h2></div><span className="section-note">Pago del 1 al 5 de cada mes</span></div><div className="pricing-grid">{plans.map(plan=><article className="pricing-card" key={plan.name}><span className="pricing-label">{plan.name}</span><h3>{plan.title}</h3><strong>{plan.price}</strong><span className="pricing-period">{plan.period}</span><ul>{plan.items.map(item=><li key={item}><CheckCircle2 size={15}/>{item}</li>)}</ul><a className="btn secondary full" href="https://socios.pedidosya.com.ar/es" target="_blank" rel="noreferrer">Registrá tu negocio</a></article>)}</div><p className="pricing-note">En el Plan 3, la inversión publicitaria de Google Ads es independiente del fee profesional mensual y corresponde exclusivamente a pauta publicitaria.</p></section>

<section className="market-section commercial-cta"><div><span className="kicker">¿QUERÉS SUMAR TU NEGOCIO?</span><h2>Registralo y empezá a construir tu presencia local.</h2></div><a className="btn primary" href="https://socios.pedidosya.com.ar/es" target="_blank" rel="noreferrer">Registrá tu negocio <ArrowUpRight size={16}/></a></section>
</main><PublicFooter/></div>}