export type Zone='las-heras'|'maipu';
export type CategoryKey='kioscos'|'talleres'|'repuestos'|'cerrajerias'|'ferreterias'|'pinturerias'|'minimercados'|'autos-usados';
export type Product={slug:string;name:string;description:string;price?:string;imageLabel:string};
export type Commerce={slug:string;name:string;category:CategoryKey;categoryLabel:string;zone:Zone;zoneLabel:string;description:string;phone:string;wa:string;address:string;hours:string;accent:string;products:Product[];services:string[];promos?:string[];mapQuery:string};

export const categories={kioscos:'Kioscos',talleres:'Talleres',repuestos:'Repuestos',cerrajerias:'Cerrajerías',ferreterias:'Ferreterías',pinturerias:'Pinturerías',minimercados:'Minimercados','autos-usados':'Autos usados'} as const;
export const zones={ 'las-heras':'Las Heras', maipu:'Maipú' } as const;
export const commerces:Commerce[]=[
{slug:'kiosco-la-esquina',name:'Kiosco La Esquina',category:'kioscos',categoryLabel:'Kiosco',zone:'las-heras',zoneLabel:'Las Heras',description:'Todo lo que necesitás para una pausa rápida, cerca de casa.',phone:'261 555 1040',wa:'5492615551040',address:'Av. Boulogne Sur Mer 742, Las Heras, Mendoza',hours:'08:00–23:30',accent:'orange',mapQuery:'Av. Boulogne Sur Mer 742, Las Heras, Mendoza',products:[{slug:'bebidas',name:'Bebidas frías',description:'Consultá sabores y disponibilidad.',price:'$ 2.500',imageLabel:'01'},{slug:'snacks',name:'Snacks',description:'Consultá por este producto.',price:'$ 1.800',imageLabel:'02'},{slug:'golosinas',name:'Golosinas',description:'Consultá por este producto.',price:'$ 1.200',imageLabel:'03'}],services:['Recargas virtuales','Pago de servicios'],promos:['2 gaseosas + snack — promo del día']},
{slug:'mendoza-motor',name:'Mendoza Motor',category:'talleres',categoryLabel:'Taller mecánico',zone:'las-heras',zoneLabel:'Las Heras',description:'Mecánica general, diagnóstico y mantenimiento para autos y utilitarios.',phone:'261 555 2211',wa:'5492615552211',address:'Av. San Martín 1840, Las Heras, Mendoza',hours:'08:30–19:00',accent:'blue',mapQuery:'Av. San Martín 1840, Las Heras, Mendoza',products:[{slug:'filtros',name:'Filtros',description:'Consultá compatibilidad.',price:'$ 12.000',imageLabel:'01'},{slug:'aceites',name:'Aceites',description:'Consultá viscosidad y stock.',price:'$ 18.000',imageLabel:'02'},{slug:'pastillas',name:'Pastillas de freno',description:'Consultá por vehículo.',price:'$ 35.000',imageLabel:'03'}],services:['Diagnóstico computarizado','Frenos y suspensión','Service completo']},
{slug:'andes-motor-seleccion',name:'Andes Motor Selección',category:'autos-usados',categoryLabel:'Taller + compra/venta',zone:'maipu',zoneLabel:'Maipú',description:'Servicio mecánico y vehículos usados revisados en Mendoza.',phone:'261 555 3322',wa:'5492615553322',address:'Ozamis 2460, Maipú, Mendoza',hours:'09:00–20:00',accent:'violet',mapQuery:'Ozamis 2460, Maipú, Mendoza',products:[{slug:'aceites',name:'Aceites',description:'Consultá stock.',price:'$ 18.000',imageLabel:'01'},{slug:'baterias',name:'Baterías',description:'Consultá compatibilidad.',price:'$ 95.000',imageLabel:'02'},{slug:'neumaticos',name:'Neumáticos',description:'Consultá medidas.',price:'$ 140.000',imageLabel:'03'}],services:['Diagnóstico precompra','Service','Revisión integral'],promos:['Financiación a convenir']},
{slug:'repuestos-cuyo',name:'Repuestos Cuyo',category:'repuestos',categoryLabel:'Casa de repuestos',zone:'maipu',zoneLabel:'Maipú',description:'Repuestos y accesorios para las marcas más buscadas.',phone:'261 555 4477',wa:'5492615554477',address:'Videla Castillo 1120, Maipú, Mendoza',hours:'08:30–18:30',accent:'green',mapQuery:'Videla Castillo 1120, Maipú, Mendoza',products:[{slug:'correas',name:'Correas',description:'Consultá compatibilidad.',price:'$ 22.000',imageLabel:'01'},{slug:'bujias',name:'Bujías',description:'Consultá por vehículo.',price:'$ 16.000',imageLabel:'02'},{slug:'pastillas',name:'Pastillas',description:'Consultá disponibilidad.',price:'$ 35.000',imageLabel:'03'}],services:['Consulta por compatibilidad','Pedido por WhatsApp']},
{slug:'cerrajeria-centro-24h',name:'Cerrajería Centro 24h',category:'cerrajerias',categoryLabel:'Cerrajería',zone:'las-heras',zoneLabel:'Las Heras',description:'Cerrajería de urgencia y soluciones para hogares, comercios y vehículos.',phone:'261 555 5500',wa:'5492615555500',address:'España 520, Las Heras, Mendoza',hours:'24 horas',accent:'red',mapQuery:'España 520, Las Heras, Mendoza',products:[],services:['Urgencias 24h','Apertura de puertas','Cambio de cerraduras','Llaves codificadas']},
{slug:'ferreteria-el-andino',name:'Ferretería El Andino',category:'ferreterias',categoryLabel:'Ferretería',zone:'las-heras',zoneLabel:'Las Heras',description:'Herramientas, materiales y soluciones para obra, hogar y mantenimiento.',phone:'261 555 6633',wa:'5492615556633',address:'Belgrano 1635, Las Heras, Mendoza',hours:'08:00–19:30',accent:'amber',mapQuery:'Belgrano 1635, Las Heras, Mendoza',products:[{slug:'taladros',name:'Taladros',description:'Consultá marcas y stock.',price:'$ 85.000',imageLabel:'01'},{slug:'pinturas',name:'Pinturas',description:'Consultá colores.',price:'$ 15.000',imageLabel:'02'},{slug:'tornilleria',name:'Tornillería',description:'Consultá medidas.',price:'$ 2.000',imageLabel:'03'}],services:['Corte de llaves','Asesoramiento']},
{slug:'pinturas-cordillera',name:'Pinturas Cordillera',category:'pinturerias',categoryLabel:'Pinturería',zone:'maipu',zoneLabel:'Maipú',description:'Pinturas, colores y asesoramiento para renovar tus espacios.',phone:'261 555 7744',wa:'5492615557744',address:'Arístides Villanueva 880, Maipú, Mendoza',hours:'08:30–19:00',accent:'pink',mapQuery:'Arístides Villanueva 880, Maipú, Mendoza',products:[{slug:'latex',name:'Látex interior',description:'Consultá color y presentación.',price:'$ 28.000',imageLabel:'01'},{slug:'esmalte',name:'Esmalte sintético',description:'Consultá stock.',price:'$ 19.000',imageLabel:'02'},{slug:'impermeabilizante',name:'Impermeabilizante',description:'Consultá cobertura.',price:'$ 32.000',imageLabel:'03'}],services:['Preparación de colores','Asesoramiento técnico'],promos:['10% en látex interior esta semana']},
{slug:'mini-mercado-san-juan',name:'Mini Mercado San Juan',category:'minimercados',categoryLabel:'Minimercado',zone:'maipu',zoneLabel:'Maipú',description:'Compras de todos los días, rápidas y cerca de vos.',phone:'261 555 8855',wa:'5492615558855',address:'San Juan 1350, Maipú, Mendoza',hours:'07:30–22:30',accent:'teal',mapQuery:'San Juan 1350, Maipú, Mendoza',products:[{slug:'almacen',name:'Almacén',description:'Consultá disponibilidad.',price:'$ 4.500',imageLabel:'01'},{slug:'bebidas',name:'Bebidas',description:'Consultá marcas.',price:'$ 2.500',imageLabel:'02'},{slug:'lacteos',name:'Lácteos',description:'Consultá stock.',price:'$ 3.500',imageLabel:'03'}],services:['Delivery en zona','Pedidos por WhatsApp'],promos:['Envío gratis desde $18.000']}
];
export function getCommerce(slug:string){return commerces.find(c=>c.slug===slug);}
export function getCategory(slug:string){return Object.hasOwn(categories,slug)?{slug,name:categories[slug as keyof typeof categories]}:undefined;}
